;;; Scheme Recursive Art Contest Entry
;;;
;;; Please do not include your name or personal info in this file.
;;;
;;; Title: A daily dose of Nezuko for final szn 
;;;
;;; Description:
;;;     Like title.
;;;     Vote.
;;;
;;; Scheme Recursive Art Contest Entry
(speed 1000)
;;;
(define (eyes)
  (begin_fill) 
  (color "#E3a6b4")
  (circle 20)
  (end_fill)
  (penup)
  (left 90)
  (forward 5)
  (right 90)
  (pendown)
  (begin_fill)
  (color "#e82a6a")
  (circle 15)
  (end_fill)
  (penup)
  (left 90)
  (forward 6)
  (right 90)
  (pendown)
  (begin_fill)
  (color "black")
  (circle 7)
  (end_fill)
  (penup)
  (right 90)
  (forward 3)
  (left 90)
  (forward 3)
  (pendown)
  (begin_fill)
  (color "#D6D6D0")
  (circle 5)
  (end_fill)
  )

(define (browsright x)
    (color "black")
    (if (= x 0)
        (hideturtle)
        (begin
            (right 6)
            (forward 4)
            (browsright (- x 1))
          )
        )
  )
(define (browsleft x)
    (color "black")
    (if (= x 0)
        (hideturtle)
        (begin
            (left 6)
            (forward 4)
            (browsleft (- x 1))
          )
        )
  )
(define (brows)
    (browsleft 12)
    (left 90)
    (forward 1)
    (left 95)
    (browsright 12)
    (right 90)
    (forward 1)
    (right 95)
    (browsleft 12)
    (left 90)
    (forward 1)
    (left 95)
    (browsright 12)
    (right 90)
    (forward 1)
    (right 95)
    (browsleft 12)
)

(define (curveleft x)
    (if (= x 0)
        (hideturtle)
        (begin
            (forward 5)
            (left 3)
            (curveleft (- x 1))
          )
  )
)
(define (curveright x)
    (if (= x 0)
        (hideturtle)
        (begin
            (forward 5)
            (right 3.3)
            (curveright (- x 1))
          )
        )
  )

(define (hair)
    (penup)
    (setheading 0)
    (setposition 1 1)
    (forward 180)
    (left 90)
    (forward 90)
    (right 90)
    (pendown)
    
    (left 90)
    (curveleft 30)
    (forward 150)
    (penup)
    (setheading 0)
    (setposition 1 1)
    (forward 180)
    (left 90)
    (forward 100)
    (right 180)
    (pendown)
    (begin_fill)
    (color "black")
    (curveright 30)

    (setheading 180)
    (forward 150)
    (left 90)
    (forward 50)
    (left 90)
    (forward 200)
    (circle 140 180)
    (forward 195)
    (left 90)
    (forward 54)
    (left 90)
    (forward 150)
    (curveright 30)
    (end_fill)
)

(define (bamboo)
    (penup)
    (setheading 0)
    (setposition 1 1)
    (forward 50)
    (left 90)
    (forward 25)
    (right 90)
    (pendown)
    
    (begin_fill)
    (color "green")
    (left 90)
    (forward 150)
    (left 90)
    (forward 20)
    (left 90)
    (forward 150)
    (left 90)
    (forward 20)
    (end_fill)

  )

(define (nose)
    (color "black")
    (penup)
    (setposition 1 1)
    (setheading 0)
    (forward 125)
    (left 90)
    (forward 90)
    (setheading 180)
    (pendown)
    (curveleft 10)
    (setheading 270)
    (forward 20)

  )

(define (flower)
    (color "#eb5e7f")
    (penup)
    (setposition 1 1)
    (setheading 0)
    (forward 225)
    (pendown)
    (begin_fill)
    (circle 10)
    (end_fill)
    (begin_fill)
    (setheading 60)
    (forward 50)
    (circle 15 200)
    (forward 50)
    (setheading 0)
    (forward 50)
    (circle 15 200)
    (forward 55)
    (end_fill)
)
(define (draw)
    ;face
    (penup)
    (setheading 0)
    (setposition 1 1)
    (forward 100)
    (pendown)
    (begin_fill)
    (color "#E3D4BF")
    (circle 100)
    (end_fill)
    
    ;eyesleft
    (penup)
    (left 90)
    (forward 120)
    (right 90)
    (forward 20)
    (pendown)
    (eyes)
    (penup)
    (forward 13)
    (right 90)
    (forward 10)
    (left 90)
    (pendown)
    (left 55)
    (brows)
    

    ;eyesright
    (penup)
    (setheading 00)
    (right 180)
    (forward 9)
    (left 90)
    (forward 130)
    (left 90)
    (pendown)
    (eyes)
    (penup)
    (forward 13)
    (right 90)
    (forward 10)
    (left 90)
    (pendown)
    (setheading 310)
    (brows)

    ;hair
    (hair)

    (bamboo)

    (nose)

    (flower)
    ;(showturtle)
    ;(hideturtle)
  )

(draw)
