;;; Scheme Recursive Art Contest Entry
;;;
;;; Please do not include your name or personal info in this file.
;;;
;;; Title: <Riding the BART at Scheme's Speed>
;;;
;;; Description:
;;;   <The most efficient Bay Area public transportation ever.>

(define (draw)
  ; YOUR CODE HERE
  (begin
    (bgcolor "black")
    (color "red")
    (penup)
    (left 144)
    (forward 285)
    (pendown)
    (right 115)
    (forward 100)
    (right 60)
    (forward 230))
    (right 59)
    (forward 130)
    (left 90)
    (forward 70)
    (left 20)
    (forward 150)
    (penup)
    (right 90)
    (forward 8)
    (right 90)
    (pendown)
    (color "orange")
    (forward 152)
    (right 20)
    (forward 30)
    (penup)
    (left 90)
    (forward 8)
    (left 90)
    (pendown)
    (color "yellow")
    (forward 30)
    (right 40)
    (forward 180)
    (right 50)
    (forward 130)
    (penup)
    (right 180)
    (forward 130)
    (left 50)
    (forward 180)
    (left 40)
    (forward 30)
    (pendown)
    (forward 48)
    (right 90)
    (forward 140)
    (left 59)
    (forward 223)
    (left 60)
    (forward 20)
    (left 30)
    (forward 43)
    (right 59)
    (forward 48)
    (penup)
    (left 90)
    (forward 8)
    (left 90)
    (pendown)
    (color "purple")
    (forward 52)
    (penup)
    (forward 3)
    (left 59)
    (forward 38)
    (right 30)
    (forward 20)
    (right 60)
    (forward 50)
    (pendown)
    (color "light blue")
    (forward 160)
    (right 59)
    (forward 140)
    (right 60)
    (forward 140)
    (left 60)
    (forward 130)
    (penup)
    (right 180)
    (forward 140)
    (left 120)
    (pendown)
    (color "orange")
    (forward 170)
    (penup)
    (right 180)
    (forward 170)
    (pendown)
    (forward 146)
    (right 30)
    (forward 52)
    (penup)
    (right 180)
    (forward 60)
    (right 90)
    (forward 118)
    (left 59)
    (forward 160)
    (right 180)
    (pendown)
    (color "green")
    (forward 153)
    (right 59)
    (forward 119)
    (right 60)
    (forward 78)
    (penup)
    (right 180)
    (circle 15 230)
    (pendown)
    (color "brown")
    (circle 15 130)
    (right 180)
    (color "green")
    (forward 230)
    (hideturtle))

; Please leave this last line alone.  You may add additional procedures above
; this line.
(draw)
