;;; Scheme Recursive Art Contest Entry
;;;
;;; Please do not include your name or personal info in this file.
;;;
;;; Title: <Sea-S 61λ>
;;;
;;; Description:
;;;   <A vast and wide sea
;;;    Lambdas are all you can see
;;;    Oh look it's a shark>

;------------------Lambda Drawing Stuff--------------------------

(define (curve-lamb scale)
  (pendown)
  (color "#064273")
  (right 60)
  (circle (* scale (- 8)) 90)
  (forward (* scale 10))
  (circle (- (* scale 20)) 120)
  (left 180)
  (begin_fill)
  (circle (* scale 20) 120)
  (right 180)
  (forward (* scale 30))
  (circle (* scale 8) 60)
  (color "#74bde8")
  (end_fill)
  (circle (* scale 8) 30)
  (setheading 0)
  (penup)
)

(define (draw-small-waves num-waves)
  (if (= 0 num-waves)
    nil
    (begin
    	(forward 61.5)
     	(curve-lamb 1.5)
    	(draw-small-waves (- num-waves 1))
    )
  )
)

;--------------------------------------------------------------
(define (limb dir len)
  (left (* dir 90))
  (forward (* len 20))
  (backward (* len 20)))

(define (forTurn amt dir)
  (penup)
  (forward (* amt 100))
  (left (* dir 90))
  (pendown)
)
(define (hooman)
    (begin_fill)
    (circle 20)
    (color "#FFDBAC")
    (end_fill)
    (color "black")
    (circle 20 270)
    (right 90)
    (forward 17)
    (limb 1 1.5)
    (limb 2 1.5)
    (left 90)
    (forward 30)
    (limb 0.5 2.4)
    (limb -1 2.4)
    (left 45)
    (forTurn 0.2 -1)
    (begin_fill)
    (color "#e89c74")
    (forward 40)
    (circle 7 180)
    (forward 80)
    (circle 7 180)
    (forward 40)
    (end_fill)
    (color "black")
    (right 90)
    (forTurn 0.95 1)
    (forTurn 0.05 1)
    (forward 9)
    (forTurn .04 0)
    (circle 6 180)
    (forTurn .05 0)
    (forward 9)
  )

(define (draw)
    (penup)
    (bgcolor "#bbc8fa")
    (setposition -350 235)
    (pendown)
    (hooman)
    (penup)
    (setposition -400 125)
    (curve-lamb 9)
    (draw-small-waves 5)
    (left 90)
    (forward 70)
    (setheading 0)
    (begin_fill)
  	(color "#808080")
  	(forward 65)
  	(right 150)
  	(forward 73)
  	(end_fill)
    (setheading 90)
    (forward 28)
    (setheading 180)
    (color "#5daede")
    (pendown)
    (begin_fill)
    (forward 20)
    (right 90)
    (forward 813.5)
    (right 90)
    (forward 20)
    (end_fill)
    (penup)
    (setposition 90 130)
    (pendown)
    (color "#ffcb63")
    (begin_fill)
    (circle 65)
    (end_fill)
    (hideturtle)
    (exitonclick))

; Please leave this last line alone.  You may add additional procedures above
; this line.
(draw)