;;; Scheme Recursive Art Contest Entry
;;;
;;; Please do not include your name or personal info in this file.
;;;
;;; Title: <Your title here>
;;;
;;; Description:
;;;   <It's your masterpiece.
;;;    Use these three lines to describe
;;;    its inner meaning.>

(define black (rgb 0 0 0))

(define (moveto x y)
  (penup)
  (goto x y)
  (pendown)
)

(define (gradient r g b)
  (if (not (> r 0.8))
    (begin
      (color (rgb r g b))
      (forward 450)
      (right 90)
      (forward 0.25)
      (right 90)
      (forward 450)
      (left 90)
      (forward 0.25)
      (left 90)
      (gradient (+ r 0.005) (+ g 0.005) (+ b 0.005))
    )
  )
)

(define (rect l w)
  (begin_fill)
  (forward l)
  (right 90)
  (forward w)
  (right 90)
  (forward l)
  (right 90)
  (forward w)
  (end_fill)
)

(define (wheels)
  (begin
    (moveto -158 -48)
    (seth 0)
    (begin_fill)
    (color (rgb 0.08 0.09 0.16))
    (circle 33)
    (end_fill)
    (penup)
    (setheading 90)
    (forward 289)
    (setheading 0)
    (pendown)
    (begin_fill)
    (circle 31)
    (end_fill)
    )
)

(define (undercarriage)
  (begin
    (moveto 174 -24)
    (begin_fill)
    (color (rgb 0 0 0))
    (seth -90)
    (forward 34)
    (left -56)
    (forward 30)
    (left 56)
    (forward 52)
    (left 55)
    (forward 38)
    (left 35)
    (forward 10)
    (left -90)
    (forward 192)
    (left -90)
    (forward 7)
    (left 34)
    (forward 40)
    (left 56)
    (forward 50)
    (left 59)
    (forward 30)
    (left -59)
    (forward 17)
    (seth -175)
    (forward 14)
    (seth 102)
    (forward 68)
    (seth 90)
    (forward 300)
    (seth 68)
    (forward 59)
    (seth 0)
    (forward 9)
    (end_fill)
  )
)

(define (top)
  (begin
    (moveto -240 5)
    (begin_fill)
    (color (rgb 0.74 0.76 0.79))
    (seth 72)
    (forward 175)
    (left -26)
    (forward 277)
    (seth -92)
    (forward 400)
    (end_fill)
  )
)

(define (windows)
  (begin
    (moveto -190 13)
    (begin_fill)
    (color (rgb 0 0 0))
    (seth 72)
    (forward 126)
    (seth 97)
    (forward 93)
    (seth 169)
    (forward 17)
    (seth -93)
    (forward 216)
    (end_fill)
  )
)

(define (trims)
  (begin
    (moveto 174 25)
    (seth 90)
    (color (rgb 1 1 1))
    (pendown)
    (begin_fill)
    (rect 50 100)
    (moveto -250 0)
    (seth 175)
    (pendown)
    (rect 100 50)
    (seth -18)
    (moveto -250 2)
    (rect 25 25)
    (moveto 174 -33)
    (pendown)
    (begin_fill)
    (seth -112)
    (forward 59)
    (seth -90)
    (forward 300)
    (seth -78)
    (forward 68)
    (seth 180)
    (forward 50)
    (seth 90)
    (forward 400)
    (goto 174 -33)
    (end_fill)
  )
)

(define (draw)
  (speed 10)
  (top)
  (windows)
  (moveto -250 5)
  (seth 88)
  (gradient 0.20 0.23 0.29)
  (undercarriage)
  (trims)
  (wheels)
  (ht)
  (exitonclick))
; Please leave this last line alone.  You may add additional procedures above
; this line.
(draw)